name: Bug Report
description: File a bug report
title: "[Bug]: "
labels: ["bug"]

body:
  - type: input
    id: phoenix-version
    attributes:
      label: Phoenix Version
      placeholder: ex. 1.8.0-rc.4
    validations:
      required: true

  - type: input
    id: elixir-version
    attributes:
      label: Elixir Version
      placeholder: ex. 1.18.1
    validations:
      required: true

  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      placeholder: Describe the bug and what you expected to happen
    validations:
      required: true

  - type: textarea
    id: reproduction-steps
    attributes:
      label: Steps to Reproduce
      placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. See error
    validations:
      required: true

  - type: textarea
    id: error-logs
    attributes:
      label: Error Logs
      render: shell
      placeholder: Paste any relevant error messages

  - type: dropdown
    id: environment
    attributes:
      label: Environment
      options:
        - Development
        - Staging
        - Production
    validations:
      required: true
