name: Feature Request
description: Suggest an idea for this project
title: "[Feature]: "
labels: ["enhancement"]

body:
  - type: textarea
    id: problem-statement
    attributes:
      label: Problem Statement
      placeholder: What problem does this feature solve?
    validations:
      required: true

  - type: textarea
    id: proposed-solution
    attributes:
      label: Proposed Solution
      placeholder: Describe the solution you'd like
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      placeholder: Alternative solutions you've considered

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      options:
        - Low
        - Medium
        - High
        - Critical

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      placeholder: Any additional context or screenshots
