name: Deploy

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test:
    uses: ./.github/workflows/ci.yml

  deploy:
    name: Deploy
    runs-on: ubuntu-20.04
    needs: test
    if: github.ref == 'refs/heads/main'

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Deploy
      run: |
        echo "Deployment would happen here"
        echo "Configure your deployment method"